### ISSUE TITLE
Issue on /notes/2022-09-26.md, line 99-100

### ISSUE THREAD

**Issue by JacDauph** [introcompsys/fall2022#9]
The reflection questions seem to be missing for the review section on the 2022-09-26 notes, in addition to the review section. I wasn't sure if the reflection questions referred to the list in the above section going through the hardware simulation test, however, it would be clearer either way to list the questions below the review section where they apply.

**Comment by brownsarahm** [comment]
this was closed by #39686d15b4605a57e94c49bcbff15cf0ec44db2d
